### ISSUE TITLE
Support for Firefox iOS

### ISSUE THREAD

**Issue by TauseefMalik** [rugk/offline-qr-code#101]
Hello Folks, Are you planning to support this add-on for Firefox web browser on iPhone?

**Comment by rugk** [comment]
I cannot even select it in the Firefox add-ons dev page.

Actually I had a quick look and [Firefox for iOS](https://support.mozilla.org/kb/add-ons-firefox-ios) does not seem to support add-ons.

As such, this is unfortunately not possible.

**Comment by TauseefMalik** [comment]
@rugk I would like to contribute to this project!

**Comment by rugk** [comment]
Sure, just go on and have a look at the CONTRIBUTING.md for getting started and choose an issue. (The "good first issues" are easy ones to get started.)
