### ISSUE TITLE
Remember last size does work as expected

### ISSUE THREAD

**Issue by TauseefMalik** [rugk/offline-qr-code#102]
I changed the QR code size option to 'remember the last size' but it could not restore to the previous size on next launch.
Windows 10
Firefox 60.0.2

**Comment by AmauriAires** [comment]
May I help with this?

**Comment by rugk** [comment]
If you can, sure. Totally have a look.
I had to look at the feature several times, it is still quite fragile. Or maybe this is a regression in the v1.2?


BTW for debugging best use [the debugger](https://mozilladevelopers.github.io/playground/debugger/). Just in case you did not know about this.☺

**Comment by AmauriAires** [comment]
Thanks for letting me know about the debugger. I will keep you updated.

**Comment by AmauriAires** [comment]
Done. I have made a pull request. Please let me know if the solution was satisfactory. I would like to actively contribute to this project.

**Comment by rugk** [comment]
BTW I think when this is fixed, I'll release it as a hotfix, because it is an annoying bug and it should not stay unfixed until v1.3.

**Comment by rugk** [comment]
Release with hotfix is published and live!

**Comment by rugk** [comment]
Release with hotfix is published and live!
