### ISSUE TITLE
Use custom error classes instead of string message checking

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#110]
Just some code style:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#Custom_Error_Types

In some areas of the code, I still check the error message, which is not really the nice way. 😄

**Comment by ParkourKarthik** [comment]
I would love to take up this issue. Could you give me some specific examples if possible?

**Comment by rugk** [comment]
Good point, I also have to search for it first.

But here you do:
https://github.com/rugk/offline-qr-code/blob/bb995062322e0806071f114fcabf904897c291ed/src/popup/modules/UserInterface.js#L416

This lines checks the error message by it's string. That's not good code style.
I did not yet quickly find more such places, actually it may be the only one. :smiley: Anyway, when creating the PR, consider that one may want to add more custom error classes in the future.
Also, of course, use the modern ES6 approach, not stuff like prototype extending.

**Comment by ParkourKarthik** [comment]
While trying to debug using "Load Temporary Add-on", I couldn't see the "popup/modules/UserInterface.js" file being loaded/visible in the Debugger window, even after clicking on the extension popup. Other important js files are already there.

I could see that the above file is loaded through InitQrCode.js (also not in debugger window) which is imported in the qrcode.js:
https://github.com/rugk/offline-qr-code/blob/27cf578e370638004a1ab926f2dc7bb51c5b6f14/src/popup/modules/InitQrCode.js#L7
https://github.com/rugk/offline-qr-code/blob/27cf578e370638004a1ab926f2dc7bb51c5b6f14/src/popup/qrcode.js#L5

**Am i missing something here?**

For ref:
![image](https://user-images.githubusercontent.com/9585305/43498022-9e714956-9562-11e8-90df-e38ea0a39d9f.png)

**Comment by rugk** [comment]
Yeah, sometimes the debugger has asome problems with ES6 modules, as it seems. Try reloading the add-on, pinning the popup window (select "do not close popups"), re-opening the debugger or so... I know, that sometimes it works and displays the modules.

**Comment by ParkourKarthik** [comment]
Did I miss saying that I already did "Disable popup auto-hide" and checked it.:blush: The same result. 
Is it possible to debug through any other means?
Tried debugging through VSCode with the launch configurations and `firefox -start-debugger-server` command, though it shows the tabs being opened in firefox, I don't get how to link the code with the extension.

**Comment by rugk** [comment]
> I don't get how to link the code with the extension.

Just "start" the add-on with F5. VSCode should then load it into FF and then do all debugging and stuff.
That's the only other way I know. Or, of course, poor debugging with `console.log` or similar statements, is the last thing you can try...
Or maybe try [web-ext](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Getting_started_with_web-ext). This can reload your add-on and do stuff like that - though debugging still needs to be done via the internal FF debugger.

Depends on what exactly you want to do.

**Comment by ParkourKarthik** [comment]
> Did not you get it to work by reloading the add-on and re-opening the debugger?

This did work as I tested by changing the source code a little and was reflected while reloading the extension.

What I thought of doing is to set a debug breakpoint in UserInterface.js on the catch statement that you have mentioned.

Anyway, I tried figuring out certain things:

- This statement is used to differentiate between error caused due to user cancellation and other errors.
https://github.com/rugk/offline-qr-code/blob/27cf578e370638004a1ab926f2dc7bb51c5b6f14/src/popup/modules/UserInterface.js#L416
- The above part receives the error from the promise returned by 
https://github.com/rugk/offline-qr-code/blob/27cf578e370638004a1ab926f2dc7bb51c5b6f14/src/background/modules/BrowserCommunication.js#L77
 
Since this message is returned by the `downloads` API, should we create a CustomError based on the message returned from the promise?

**Comment by rugk** [comment]
> should we create a CustomError based on the message returned from the promise?

Puuh… difficult question. I'd say, at least not dynamically… or… As the message is also just some string encapsulated in an `Error` object that the API returns.
So generally you may wrap the error (or the error.message?) in a new custom Promise.

But seeing 
https://github.com/rugk/offline-qr-code/blob/27cf578e370638004a1ab926f2dc7bb51c5b6f14/src/popup/modules/UserInterface.js#L416

I am not sure right now, whether that code part is even reached, currently. That could make testing… well… harder.
Because the problem there is the popup is already closed, when the user sees the permission request for downloading or the download window.
So mhh… maybe I do not even use the "check string" antipattern anywhere, where it matters.

**Comment by ParkourKarthik** [comment]
>I am not sure right now, whether that code part is even reached, currently. That could make testing… well… harder.
Because the problem there is the popup is already closed, when the user sees the permission request for downloading or the download window.
So mhh… maybe I do not even use the "check string" antipattern anywhere, where it matters.

well... what should i do now ?😕

**Comment by rugk** [comment]
Also an issue seems to be that this is an exception of the system, so what you've said earlier:
> Since this message is returned by the downloads API, should we create a CustomError based on the message returned from the promise?

I begin to doubt this is useful.

So unless yo find another possibility, where a custom error would be useful, I think we can close this issue, sorry. 😄 

If you want, you may have a look [at a different nice good first issue](https://github.com/rugk/offline-qr-code/labels/good%20first%20issue).
