### ISSUE TITLE
Contrast color algorithm

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#117]
Result of https://github.com/rugk/offline-qr-code/pull/86

I am currently creating unit tests (see https://github.com/rugk/offline-qr-code/pull/116) and began with the Colors module, because it is quite easy.

Now, I checked the `invertColor` and it failed:

![image](https://user-images.githubusercontent.com/11966684/43688766-7cc215d4-98ef-11e8-8ba3-3ecd7eab28c6.png)

(You can run these tests by yourself. Everything is explained in the branch/PR I've linked.)

For reference colors/"inverter" I just used the one [DuckDuckGo provides](https://duckduckgo.com/?q=%234F477D&t=ffab&ia=answer). ([first color here](https://duckduckgo.com/?q=%2300feff&t=ffab&ia=answer))

So, especially for the first cyan color, I think, there is this "color wheel", where it can be clearly seen (and one may know it, too :laughing:), that cyan is the "opposite" of red:

![image](https://user-images.githubusercontent.com/11966684/43688864-4e6689de-98f1-11e8-91c4-268dfa66d1d3.png)
<small>By Jacobolus - Own work, CC BY-SA 3.0, https://commons.wikimedia.org/w/index.php?curid=12405869</small>

So I guess, we have an error in the calculation.

Or can you explain it in a different way? E.g. if you can provide me a reference "color inverter" that emits the same colors as our implementation here does, that _may_ solve this problem, or, help, at least.

/to @ENT8R
/cc @LMLB

**Comment by rugk** [comment]
Okay, I see something: The DDG color generator returns the same opposite color (red) for these both colors:
* `#00FFFF` - real cyan
* `#00FEFF` - [teal50](https://design.firefox.com/photon/visuals/color.html#teal)

Also same analogous colors, so mhh… :thinking:

**Comment by LMLB** [comment]
The one DuckDuckGo provides (which is actually color-hex.com) inverts the hue but keeps the same brightness (in HSL/HSV). `invertColor` just inverts each RGB color channel (which inverts both the hue and the brightness). I found [https://pinetools.com/invert-color](https://pinetools.com/invert-color) which also just inverts each RGB color channel.

**Comment by rugk** [comment]
Hmm, okay, thanks for the info. So what may be better suited for generating a contrast value when you need it for the QR code?

**Comment by LMLB** [comment]
I would go with the `invertColor` you have now, since difference in brightness is more important than difference in hue.

**Comment by rugk** [comment]
Okay, but see [this issue](https://github.com/rugk/offline-qr-code/issues/92#issuecomment-394178142). Maybe it could be different when not inverting the brightness?

**Comment by rugk** [comment]
So I just found https://github.com/onury/invert-color and it looks like a nice lib that only does hue rotation. As that seems to be really a little more complicated.

**Comment by rugk** [comment]
[This "designer" discussion](https://stackoverflow.com/questions/946544/good-text-foreground-color-for-a-given-background-color) is quite interesting, however, in our case we of course do not really care about perceived color of humans/the user, but actually the technical contrast.

**Comment by rugk** [comment]
https://github.com/rugk/offline-qr-code/commit/fe836a0ab735e442dcbb591425d800f6ec45d131 added this as expected. Don't know what else we could change… https://github.com/rugk/offline-qr-code/issues/92 seems to track the actual work.
