### ISSUE TITLE
Remove "Settings" menu from menu icon

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#119]
In Firefox 62 a new "Manage extension" menu item for _all_ add-on icons has been introduced. As such, our own "Settings" menu is redundant now, as it leads to the same page.

As such, we have to remove it.

**Comment by rugk** [comment]
As you can see from the link above your comment, @danielrsilver did a PR for this (https://github.com/rugk/offline-qr-code/pull/122). However, it was not properly what I wanted to be done in this issue, so the PR could not be merged. I also have not heard back from @danielrsilver.
As such, I guess, it is okay for you to pick this. 😄

**Comment by JoshCooperr** [comment]
Hey @rugk,
I have written a fix for this locally but cannot create a branch on the repo to submit a PR as I do not have the correct permissions. If this still needs to be fixed then I can push that as soon as I have permission to.

**Comment by rugk** [comment]
Ah, great. [Here is how you for a repo](https://help.github.com/articles/fork-a-repo/#propose-changes-to-someone-elses-project) and then [submit a PR](https://help.github.com/articles/creating-a-pull-request/), which I can then merge.
