### ISSUE TITLE
Add function for RandomTips specs

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#123]
It should be possible to add a [function here](https://github.com/rugk/offline-qr-code/blob/unit/src/common/modules/data/tips.js) as a requirement for an add-on and use it to always force or always hide showing an tip.

It:
* should get the tip settings passed, to make something out of it, better pass all of them, so the function could correlate different tips e.g.
* maybe it's possible to do with one function returning true/false for show/hide (or null for usual behavior)
* maybe add one that overwrites the usual behavior, and one, that does not
* add unit tests (first, test-driven dev.-like :smile:)

**Comment by baymac** [comment]
Hey rugk, the hyperlink to your function is an invalid url. Can you update it so that I can proceed?

**Comment by rugk** [comment]
Oh, yeah here you go:
* here is the module and function it likely has to go into: https://github.com/rugk/offline-qr-code/blob/master/src/common/modules/RandomTips.js#L128
* here is the data for all tips: https://github.com/rugk/offline-qr-code/blob/master/src/common/modules/data/tips.js

**Comment by rugk** [comment]
@baymac Still interested in it?

**Comment by baymac** [comment]
Yeah, I was little busy with some other stuff so totally forgot about this. Now that I am free, I am looking it. Thanks for reminding. :)

**Comment by rugk** [comment]
Yeah, see also I just came up [with an actual use case of this feature in this add-on](https://github.com/rugk/offline-qr-code/issues/150).

Also note that [the module](https://github.com/TinyWebEx/RandomTips), where this is to be added now lives in a new separate repository due to refactoring and trying to decouple it from this project. (As such, the links have changed again… 😑, but I think in the smaller module you'll find the place where it is supposed to be put. :wink:)

**Comment by rugk** [comment]
@baymac Any news?

**Comment by rugk** [comment]
Okay, so I'll do it myself now.
