### ISSUE TITLE
Localization of dialog for error correction

### ISSUE THREAD

**Issue by kinafu** [rugk/offline-qr-code#139]
(At least) in German the levels are named
"medium" "low" and so on.

Should be "niedrig", "hoch" (in German) etc.

**Comment by rugk** [comment]
Yeah, however I left them in English in the translation as they would not (always) match the abbreviations (L – Low, M – Medium, Q – Q) in all languages.
It's also exactly the same way as they are written in Wikipedia article: https://de.wikipedia.org/wiki/QR-Code#Kapazit%C3%A4t_und_Fehlertoleranz

**Comment by rugk** [comment]
Closing for now, as I'd say it's okay to stay to Wikipedia. Don't know what their rationale is though…

If anyone has any better idea, feel free to comment.
