### ISSUE TITLE
Improve internationalization of quiet zone option text near range slider

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#140]
In https://github.com/rugk/offline-qr-code/pull/129 @xlomonosvx added an option to add the quiet zone.

What issue that I spotted in the options is just a (currently, theoretical) one when localizing/translating it. Actually there are two things:
* first, there may be languages that place the number somewhere else e.g. "module 1" or "module 1 de bla" or something like that. 
* secondly, we need to account/change the version of the text depending on the number itself, i.e. for one it has to be "1 module", for 2 "2 modules" etc.

HTML is here:
https://github.com/rugk/offline-qr-code/blob/master/src/options/options.html#L114-L117

This may need changes in:
* the Localiser to support placeholders (or not, if only done by JS)
* the update function should use placeholders or so to localize it correctly

**Comment by mcorwin22** [comment]
Hi, I would like to help out on this. I have cloned the project and have what looks to be a working version. Thanks.

**Comment by rugk** [comment]
@mcorwin22 Yeah, just load the default one in `src/`. For easier contributing that already _is_ the dev manifest. I only switch them out when building releases. :smile:
