### ISSUE TITLE
Cannot generate tabs for download (URLs) opened in new tab

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#146]
STR: https://github.com/rugk/offline-qr-code/issues/144

I guess this is totally an ("upstream") bug of Firefox, or just expected behaviour. I mean, why should not it be possible to get the tab URL of a downloaded file. It is very certainly displayed in the URL bar, so this

Other things like (tab parents) can be retrieved. ([tested with this](https://addons.mozilla.org/firefox/addon/how-did-i-get-here/))

So either this needs to be fixed here or reported to Firefox.

**Comment by Wikinaut** [comment]
I don't know, if it is a FF bug. Could be (I am not sure), that this is a security feature.

**Comment by rugk** [comment]
Okay, thinking about it, as I only request the "activeTab" permission, this does not count as an _active_ tab?

This just needs soem testing. (e.g. to verify what I've just said, change the permission from "activeTab" to "tabs" :smile:)

**Comment by rugk** [comment]
Okay, so as I suspected it's a permission error. When you change the permission to "tabs" you also just get `about:blank`, so this does not help very much. (It seems that the tab is really a blank one, and does not have the URL in it, but just the "fake" link put into it.)
This blocked by upstream https://bugzilla.mozilla.org/show_bug.cgi?id=1510215.

**Comment by rugk** [comment]
As we suspected, it is expected/a technical limitation:
> "about:blank" is the expected URL of the tab.

https://bugzilla.mozilla.org/show_bug.cgi?id=1510215#c2

So I'll close this as it is not fixable by me.
