### ISSUE TITLE
Version problem?  Latest Firefox installed, but add-on page says "Requires latest Firefox"

### ISSUE THREAD

**Issue by dscotese** [rugk/offline-qr-code#153]
![image](https://user-images.githubusercontent.com/1767796/50405254-99ce3f00-0766-11e9-85c7-88d6cac3e78f.png)
As you see, the add-on page behaves as if my browser needs to be updated, but my browser says that it's up to date.

**Comment by rugk** [comment]
That looks more like an issue of Firefox/the addons.mozilla.org site, but we need more information here to troubleshoot this:
* Does this happen for other add-ons, too?
* What is your system? What is your user agent (there are many websites to loook that up)?

FYI this add-on requires [Firefox 60 or higher](https://github.com/rugk/offline-qr-code/blob/5d9e44cc7634c4a80a092344016e8cd986279615/src/manifest.json#L62) so it should all work fine.

**Comment by dscotese** [comment]
I customized my useragent, so that was the problem.  Sorry about that!
