### ISSUE TITLE
Add tip to encourage users to translate add-on

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#163]
Depends on https://github.com/rugk/offline-qr-code/issues/123

A tip like "You speak another language?" -> "Help translate this add-on" could be added.

Requirements:
* could link to https://github.com/rugk/offline-qr-code/blob/master/CONTRIBUTING.md#translations, or, as that is a little bad link collection, a new FAQ
* only shown when we can assume the user is not using this add-on into their native language, i.e. check whether the language the browser requests is the same as the add-on is translated to
* could also mention that language in the hint, but that may be too creepy for some people, so rather not :wink:

**Comment by co16353sidak** [comment]
Hi, is anybody working on this or could I have a go? @rugk

**Comment by rugk** [comment]
Feel free to take this on. 😃

**Comment by rugk** [comment]
@co16353sidak If you need any pointers/help or so, feel free to ask.

**Comment by rugk** [comment]
@co16353sidak Are you still interested in it? If not, that's no problem, just add a notice, so I know what the current status of this issue is.

**Comment by co16353sidak** [comment]
I am sorry for the delays @rugk, I would love some help/pointers in figuring out how to start with this

**Comment by rugk** [comment]
Okay, so:
* the module you need to understand for this: https://github.com/TinyWebEx/RandomTips
* the code you likely need to change: https://github.com/rugk/offline-qr-code/blob/master/src/common/modules/data/Tips.js
* also, you need to make use of a custom function to evaluate to - as the requirements state -:
  > only shown when we can assume the user is not using this add-on into their native language
  For doing so, two more pointers:
  * There are some very similar issues, like https://github.com/rugk/offline-qr-code/issues/162 that I already solved in https://github.com/rugk/offline-qr-code/pull/166
  * Also generally see the requirement #1123 I linked in the top post

**Comment by rugk** [comment]
Note I really need to merge the PRs I just linked and I am doing this ASAP. Just needs a little more testing, but you can already work on branch https://github.com/rugk/offline-qr-code/pull/166 if you want (and need async operations...)

**Comment by rugk** [comment]
BTW PRs are merged.

**Comment by co16353sidak** [comment]
Sorry, @rugk give me another day to start work on this, if possible

**Comment by rugk** [comment]
Sure, no problem.

**Comment by rugk** [comment]
So, I'll implemented a different tip in https://github.com/rugk/offline-qr-code/pull/167. Maybe it helps to see some example code, there.

**Comment by rugk** [comment]
@co16353sidak How is it going?

Note that I do plan to release the next version of this add-on with this change included this weekend…

**Comment by rugk** [comment]
@co16353sidak Any news? Are you still working on this issue?

**Comment by rugk** [comment]
Seeing @co16353sidak likely abandoned this issue, I'll take it over…
