### ISSUE TITLE
(Automatic) dark mode

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#186]
## Current experience

![image](https://user-images.githubusercontent.com/11966684/56685155-95447380-66d1-11e9-9d1c-d65d86a76345.png)

on GNOME (Fedora/Linux) with Firefox 68 here.

In contrast to Firefox' own/internal popups:
![image](https://user-images.githubusercontent.com/11966684/56687928-a4c6bb00-66d7-11e9-8526-909df0a3606c.png)

### Problems

* A common issue I see on websites (but possibly also an issue of Firefox as it should not handle it like this?), is that input fields inherit the system's white font color by default.
* Generally, the white popup stands out a lot…

## Expected

1. Possibly report the first thing as an issue in Firefox. (don't know how it looks on other OSes)
2. Implement a dark mode that is triggered, when the system uses a dark theme…

To do so, there is this **new fancy** CSS media query: https://developer.mozilla.org/docs/Web/CSS/@media/prefers-color-scheme aka `prefers-color-scheme`
But should the need arise, you can use this JS API: https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia

Note: There **must not** be any manual selection of this dark mode. I'd consider this an unnecessary option…

Of course, as always, adhere to the [Photon design](https://design.firefox.com/photon).

3. (optional) As for the QR code itself, that would obviously usually also need to be inverted. So it could be an idea to also change the default colors of the QR code, if it is in dark mode. (of course, do not overwrite user settings though)
  However, this requires some JS changes (which is possible as explained above), but actually even worse: Many QR code scanners read them. (see https://github.com/rugk/offline-qr-code/issues/20)
  So, if we do so, we definitively need to implement https://github.com/rugk/offline-qr-code/issues/20 first. Or find some way that is still scannable, but looks decent in the dark mode.

### Good first issue

This is a good first issue, as it is likely a CSS only change. (And hopefully with not-so many CSS changes.)

Also any more ideas on this are appreciated. :smiley:

**Comment by davidfloyd91** [comment]
I'd be happy to take this one if it's available

**Comment by rugk** [comment]
Sure… feel free to do so.

**Comment by davidfloyd91** [comment]
So I hit an interesting snag here. `prefers-color-scheme` reads the user's preference from the OS, not the browser. If I enable dark mode on macOS Mojave (10.14.5) but select light mode on Firefox (67.0 (64-bit)), the CSS reads `prefers-color-scheme: dark` as true: 

![image](https://user-images.githubusercontent.com/31059979/58816121-d136f680-85f6-11e9-9861-d93d9db0f23e.png)

If I opt for light mode on Mac but dark mode on Firefox, `prefers-color-scheme: dark` is false:

![image](https://user-images.githubusercontent.com/31059979/58816060-b8c6dc00-85f6-11e9-8a82-381ca70dbf54.png)

It's only when both the browser and OS are set to dark (or light) that the desired behavior results:

![image](https://user-images.githubusercontent.com/31059979/58816018-a5b40c00-85f6-11e9-96ab-07e65a241767.png)

Let me know if you're alright with that. I'll look into ways to read the theme preference directly from the browser in the mean time.

(By the way this issue arises whether you use the CSS media query or JS, eg `let mql = window.matchMedia('(prefers-color-scheme: dark)');`.)

**Comment by rugk** [comment]
> Let me know if you're alright with that.

Yes, I think this is a system limitation I am totally fine with… :smile: 

> I'll look into ways to read the theme preference directly from the browser in the mean time.

Given the current APIs, i doubt it's possible [but 

> (By the way this issue arises whether you use the CSS media query or JS, eg let mql = window.matchMedia('(prefers-color-scheme: dark)');.)

Hint: I've made [an add-on to toggle that/that overrides this](https://github.com/rugk/website-dark-mode-switcher).
So I am very well aware of that, yes. :smile: 
(But of course, the add-on cannot influence other add-ons [yet], so it won't help for testing here.)

**Comment by rugk** [comment]
BTW
> reads the user's preference from the OS, not the browser

I've also already complained here about that:
https://discourse.mozilla.org/t/how-to-detect-the-dark-theme-in-a-webextension/38604?u=rugkx

**Comment by davidfloyd91** [comment]
> Given the current APIs, i doubt it's possible [but

Yeah it's not looking promising ...

> So I am very well aware of that, yes. 😄

Ha I see you've been contending with this issue for a while. Definitely seems like something FF should improve

> Yes, I think this is a system limitation I am totally fine with… 😄

In that case I'll submit a PR. Please let me know of any issues with the changes I've made. If something seems obvious, let's just say I'm taking you up on the "good-first-issue" tag here 😄
