### ISSUE TITLE
Updated translations for 'he': Hebrew (modern) (עברית)

### ISSUE THREAD

**Issue by shanirub** [rugk/offline-qr-code#192]
Hebrew translation not finished.
(Testing to see if Web Extension Translator saved current changes)

**Comment by rugk** [comment]
Uhm, no? At least in this issue you saved/I see no changes. 

AFAIK to save your changes in webext-translator click the "download ZIP" button.
(At least that's good to do before trying anything else… :smile:)

But thanks for (soon :wink:) contributing translations.

**Comment by rugk** [comment]
So https://github.com/Lusito/web-ext-translator/issues/28 might be of interest to you.

As for now, I can close this issue I guess, as the translation tool will prompt you to open a new issue anyway. But remember you can also download the ZIP and e.g. make a "usual" PR to this repo. :smiley:
