### ISSUE TITLE
Test whether auto-select retry is still needed with Firefox >= 60

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#196]
I've found these comments:

https://github.com/rugk/offline-qr-code/blob/e900c8878f86f2b3bea5558b686097b766fa9cba/src/popup/modules/UserInterface.js#L191

https://github.com/rugk/offline-qr-code/blob/e900c8878f86f2b3bea5558b686097b766fa9cba/src/popup/modules/UserInterface.js#L162

The code is responsible for selecting all the text and scrolling to the top when you open the QR code popup.

The comments indicate this is a workaround only for Firefox <= 60, but unfortunately no bug is linked or so.

However, nowadays we require Firefox 60 as a minimum version, anyway.

## TODO

* So we need to test – if we remove these workarounds –, does it still work in Firefox >= 60?
* If so, remove it from the code. (and clean up related code, if needed)

**Comment by cornu-ammonis** [comment]
@rugk If I verify that this can be removed, do you think this would also apply to the setTimeout call here? Seems like it to me
https://github.com/rugk/offline-qr-code/blob/e900c8878f86f2b3bea5558b686097b766fa9cba/src/popup/modules/UserInterface.js#L495
https://github.com/rugk/offline-qr-code/blob/e900c8878f86f2b3bea5558b686097b766fa9cba/src/popup/modules/UserInterface.js#L496

**Comment by cornu-ammonis** [comment]
@rugk I have verified the behavior does not change -- text is still selected -- if I remove the setTimeouts here. I also tracked down the original [bug here](https://bugzilla.mozilla.org/show_bug.cgi?id=1324255) which confirms that the bug was fixed in Firefox 60. 

I will open a PR to remove and cleanup!
