### ISSUE TITLE
Intendation of grey helper text not applied

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#205]
## Steps to reproduce

Possibly https://bugzilla.mozilla.org/show_bug.cgi?id=1532724

Go to about:addons of Add-on.

### Actual behavior

![image](https://user-images.githubusercontent.com/11966684/59145473-a5e04d00-89e4-11e9-8464-725315092ff5.png)
![image](https://user-images.githubusercontent.com/11966684/59145476-ac6ec480-89e4-11e9-9110-aaa761cf6410.png)

-> the grey text misses intendation

### Expected behavior

![image](https://user-images.githubusercontent.com/11966684/59145481-b98bb380-89e4-11e9-8111-416b13394122.png)

(from emoji picker)

## System

Browser and version: Firefox 69

## Possible solution

likely misses the `intend` class

**Comment by arjithn** [comment]
Hey there @rugk ! Can I take this as my first issue? I'm new to contributing

**Comment by rugk** [comment]
Yes, feel free to take this on. :smile:

**Comment by rugk** [comment]
@arjithn Any news? If you need any pointers/help or have questions, feel free to ask.

**Comment by arjithn** [comment]
Yes @rugk I would like some directions. I tried loading the extension into the browser and was able to observe the issue. However when I reloaded, without any code I am getting the right indentation

Will post some screenshots as well.

**Comment by rugk** [comment]
So, uhm, you did not change any code?

So, maybe it's already fixed. Let me check…
Okay, sorry…

I am so stupid. This is really already fixed in the master (just not released in the last version). Checking the git history reveals it's fixed in https://github.com/rugk/offline-qr-code/commit/5f418620a12d0e89e2654f17ac0b722a540af70e. I created this issue with a release version of the add-on.

I am so sorry.
Feel free [to browse any other good first issues for easy issues to start contributing](https://github.com/rugk/offline-qr-code/labels/good%20first%20issue). At least you know already know how to clone and load this add-on. :wink: 

Again sorry, but I have to close this issue as "already fixed".
