### ISSUE TITLE
AMO SEO: cannot find if searching for "qrcode"

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#207]
## Steps to reproduce

Search for "qrcode" on AMO: https://addons.mozilla.org/en-US/firefox/search/?platform=linux&q=qrcode

### Actual behavior

It is way too far on page two.

### Expected behavior

As when you search for "qr code" you get it at position 3.

**Comment by reinald28** [comment]
Expected behavior has already been achieved. The item appears first in the list.
https://addons.mozilla.org/en-US/firefox/search/?platform=linux&q=qrcode

**Comment by rugk** [comment]
Does not in my case… :thinking: (and you linked to the en-US version, or did you actually check that with another language?)

![image](https://user-images.githubusercontent.com/11966684/60031230-a0e9f180-96a4-11e9-813a-ddc72929312b.png)
