### ISSUE TITLE
Bad Reputation (avast)

### ISSUE THREAD

**Issue by fbthb** [rugk/offline-qr-code#212]
The Add-on has a bad reputation (2 of 5 stars) according to "Avast Free Antivirus". Avast asks the user to delete the Add-on. I couldn´t find the any reasons for this.

**Comment by rugk** [comment]
Previous discussion on Mastodon (in German): https://chaos.social/@madras/102512449211358516

TL;DR: Avast makes some strange internal ranking, no other add-on's affected, e.g. Awesome Emoji Picker is not reported. This has been reported to avast as a false-positive (via the website).

**Comment by rugk** [comment]
@fbthb Could you possibly also ask on the Avast forums or so. I found the German thread https://forum.avast.com/index.php?topic=201026.0. Maybe following the steps there also helps?

**Comment by rugk** [comment]
I've looked around a little more and found this:
* FAQ item "Can I prevent Avast Browser Cleanup from reporting a specific add-on as poorly rated?": This is how you can apparently whitelist the add-on, see https://support.avast.com/en-ww/article/115/#idt_3200
* In the FAQ, @fbthb, please also mind the questions below: "[Where do I find the log file for Avast Browser Cleanup?](https://support.avast.com/en-ww/article/115/#idt_3300)" Maybe you can post this? (Please remember to remove private data from it.) And "[How can I give feedback for Avast Browser Cleanup?](https://support.avast.com/en-ww/article/115/#idt_3400)" to tell them this is a false-positive.
* Also, the issue shows up in [several](https://forum.avast.com/index.php?topic=221940.0) [add-ons](https://forum.avast.com/index.php?topic=221940.0). Actually this security features sometimes even [accidentally destroys Firefox](https://techdows.com/2018/09/avast-avg-bad-add-on-warning-leads-users-to-break-firefox.html)… :roll_eyes: 

Anyway, finally just to make one thing clear: **This add-on is perfectly harmless and _not_ malicious.** As it can be seen from good user ratings, few permission etc. the add-on cannot even do anything bad and also does not. We have a clear [privacy policy](https://addons.mozilla.org/firefox/addon/offline-qr-code-generator/privacy/) and collect no data from the user.

**Comment by fbthb** [comment]
I wrote a message to the Avast-Support-Team on July, 28th. I got an answer on July, 31th, writing that they would have a look at this.
According to a new check from today, the problem seems to be solved.

**Comment by rugk** [comment]
Great to hear, thanks for the feedack.
