### ISSUE TITLE
Set download name to domain name for URLs

### ISSUE THREAD

**Issue by ArminJo** [rugk/offline-qr-code#247]
First thank you very much for developing this wonderful and very helpful Extension 👍 🥇 

## Background
Storing  multiple QR codes from URL's is tedious, since you want to rename them sensible, to know what is in there.

## Proposed solution
If we have an URL pattern :// I would like to have the download name set to the domain name (or host name if it is easier) with '.' substituted by '_' .

Is this possible?
Makes it sense for me to develop a change and issue an PR?

Greetings from Cologne
Armin

**Comment by rugk** [comment]
Theoretically possible quite easily, however there is one big usability problem: The user can change the text that is encoded in the QR code.

As such, unless they use the default URL/popup, we cannot really know what's in there…

A different idea may be to just use the first 20 (or so characters of the text that gets encoded as the name, possibly?

Thanks for the nice feedback, BTW.

**Comment by ArminJo** [comment]
Hi,
Thanks fore your rsponse.
I thought of something like:
if length of resulting text from: text | sed '|.*://[w.]*\([^/]*\)/.*|\1|'  | tr '.' '_' 
> 6 take this string as download name, else ... (use the first 20 characters is a good idea).
As you alredy know, the regular expression groups the domain in \(........\)

**Comment by rugk** [comment]
Your sed command did not work when I've tried it here (¹), but if I get this you ought to replace some usual URL chars.
I do agree with the general idea: "convert" the file name somehow and use it as a file name.

Now, however, we ought to be very careful what chars we allow. See https://perishablepress.com/stop-using-unsafe-characters-in-urls/, there are many many chars that could end up in an URL. Think of emojis, backslashes etc.
And not all of these may convert to valid file names on all OS'es (Windows hates the pipe `|` char e.g.).

As such, maybe rather use a whitelist approach for that, than a blacklist one…

Apart from all that, I think this is indeed useful and would .
Depending on how you generate the file name, that may still be a thing to discuss (in the PR) though…

¹ 
```
$ echo text | sed '|.://[w.]([^/])/.|\1|' | tr '.' '_'
sed: -e expression #1, char 1: unknown command: `|'
```

**Comment by ArminJo** [comment]
Sorry I accidentally deleted the s
echo text | sed '**s**|.://[w.]([^/])/.|\1|' | tr '.' '_'

**Comment by ArminJo** [comment]
Please help me a bit and tell me at which part / class / function of your program this change makes most sense.

**Comment by rugk** [comment]
Here the file names are set:

https://github.com/rugk/offline-qr-code/blob/01cab47e8c7f47dfa4f0e5c2ca4cdc8f42a729e8/src/popup/modules/UserInterface.js#L448-L468

For the PR, it would be good to have a new function that chooses the file name, based on the input you need (text?) and returns it there.
This function can then be adjusted/tweaked etc.

There should be a fallback to the current names, e.g. if the resulting file name is an empty string (``), which may also cause errors when saving the file.

**Comment by rugk** [comment]
To add one another thing: Maybe still prepend the domain/URL name with `qrcode-` or `qrcode_` or so, so the result is e.g. `qrcode_wikipedia-de`, so one can still easily find all images of this QR code generator. (A domain name alone for an image file could be anything)

**Comment by ArminJo** [comment]
> Maybe still prepend the domain/URL name with `qrcode-` or `qrcode_` or so

Brilliant!!! 👍 

I think I need this or the next week for implementing this.

**Comment by ArminJo** [comment]
What is the IDE you use?
I am looking for the variable containing the text converted to the QRcode and can not find it.

**Comment by rugk** [comment]
Atom and/or Visual Studio Code, but that should not matter.

You likely should be able to retrieve that in the `QrCreator` hmm…
At least it's all fet into there [for generation](https://github.com/rugk/offline-qr-code/blob/01cab47e8c7f47dfa4f0e5c2ca4cdc8f42a729e8/src/popup/modules/QrCreator.js).

Hmm, you need to look what is the best case to catch that var. IIRC, we really just feed it into there and generate it. It's saved nowhere else.
So you likely have to adjust either the `QrCreator` or read it based on the textarea input again. :thinking: (that last thing would IMHO not be a good workaround)

**Comment by ArminJo** [comment]
It worked locally for me.
Using indexOf etc. is more self documenting, therfore I did not heavily rely on regular expressions.
The PR is now ready.

**Comment by ArminJo** [comment]
Just a question, when do you plan to release this change?

**Comment by rugk** [comment]
There is currently [no release planned](https://github.com/rugk/offline-qr-code/milestone/5), but surely if these other changes are in there, I'll soon make a release.

**Comment by ArminJo** [comment]
Hello,
is there a chance to see the changes go live?
Or do you have a binary for manual install?
Thanks

**Comment by rugk** [comment]
There is no release planned yet as I did not consider this a big feature.
And there is still sth. planed till the next release: https://github.com/rugk/offline-qr-code/milestone/5

That said, I may reconsider this though.
