### ISSUE TITLE
[Enhancement] Option to hide the text box until QR code is clicked

### ISSUE THREAD

**Issue by blackICE19240** [rugk/offline-qr-code#253]
I think this would make it look a lot more tidy

**Comment by rugk** [comment]
Thanks for your idea.
However, I don't agree here.
First of all, I think there is not so much to tidy up, the add-on popup is already quite sleek and does not show anything except a QR code and a text input box.
But more importantly, such a thing would not really be intuitive. Usually people don't click on images, yet alone on QR codes, so it would be very hard to discover.
Actually, we had issues in the past that people did not even got that they can edit/enter text there to edit the QR code. See https://github.com/rugk/offline-qr-code/issues/42. As such, hiding it would just make this UX problem worse.
Finally, the box does not only have the intent of allowing you to edit the QR code content, but also to show you/give you a visual feedback of what the text encoded in the QR code actually shows. E.g. it may be not obvious to some that it *automatically* uses the URL.
Furthermore, even if you know that, it's quite handy to see the URL there again in full length (the URL bar may not show everything) – again, to give you a visual feedback.

Even as an optional feature I don't think this is very useful.

Also, please mind to use the feature issue template when reporting enhancements.

Also next time it would be helpful to describe a use case or similar idea to explain *why* an enhancement should be done.

Closing this as wontfix for the reasons described above.

**Comment by blackICE19240** [comment]
Wow, you've certainly thought that out well and you make some very good points.
Is an option in settings still out of the question?

**Comment by rugk** [comment]
> Is an option in settings still out of the question?

As I've explained above, yes.

> Wow, you've certainly thought that out well and you make some very good points.

Thanks, yes. I'll try to take user ideas into consideration and provide detailed information if I reject some idea.
So if you agree with me that'*s even better then. :wink:
