### ISSUE TITLE
Adds http:// in front of domain if it looks like an URL

### ISSUE THREAD

**Issue by phioe** [rugk/offline-qr-code#254]
I'm using QR generators mainly to exchange information between desktop and mobile, i.e. 
copy s.th. on desktop PC → open qr-code → paste into textarea → scan QR with mobile → continue on mobile

Obviously, if the content "looks like an URL", offline-qr-code generates an URI type qr-code and with scanning, a "http://" is added in front. 

That could be useful for real URLs but need edit in case of e.g. mailservers speaking POP3, IMAP or SMTP (or think of any other domain use besides WWW links). But when I copy **_sslpop.domain.tld_** to the textarea of offline-qr-code, I don't want a **_http://sslpop.domain.tld_** in my destination clipboard. 

There seems to be no setting for a default (like I would need plain text here) or a possibility to select, as far as I can see. Am I overlooking something?

Best
Philipp

**Comment by rugk** [comment]
First of all, next time please fill out the issue template you choose.

> But when I copy sslpop.domain.tld to the textarea of offline-qr-code, I don't want a http://sslpop.domain.tld in my destination clipboard.

I just tried to reproduce this. And it does not do this.

![grafik](https://user-images.githubusercontent.com/11966684/87248106-cdabab00-c457-11ea-89e3-7087cf038ed5.png)

If I can it with my QR code reader, it is read as `sslpop.domain.tld` (17 chars).
I use _Binary Eye_ on Android.

As such, the behavior you describe, is not actually intended.

Only if you use the default QR code, that is generated when you open the popup, an URL is generated in the QR code. Of course,m however, it just uses the URL from the URL bar. Maybe the protocol (`https://` or so) is hidden there, but in general the add-on does not mangles with the content. It just uses the URL/text input, as it is…

As an suggestion, maybe check your QR code _scanner_ and try out a different one. Maybe this is the part that "tries to be" "clever" here? :thinking:

**Comment by phioe** [comment]
> As an suggestion, maybe check your QR code scanner and try out a different one. Maybe this is the part that "tries to be" "clever" here?

🤦‍♂️ That seems to be the cause. I used to use "Barcode Scanner", but I didn't spot any (obviously) related setting that could have caused that. Tried also Binary Eye and this works fine, so I'll stay with that. Thanks.

Bye
Philipp
