### ISSUE TITLE
To disable it in context menu

### ISSUE THREAD

**Issue by Hochiss** [rugk/offline-qr-code#264]
## Background
Firefox extension context menu is getting messy.

## Proposed solution
please give an option in preference to disable it in context menu

## Alternatives
That was the reason I uninstalled another QR code extension.

Thanks!

**Comment by rugk** [comment]
Yeah, it's only one entry, but it's a valid feature request. This is a dupe of https://github.com/rugk/offline-qr-code/issues/157 though, so see there for how to implement it. (Note this is an easy issue, so a PR would be gladly appreciated.)

**Comment by rugk** [comment]
Duplicate of https://github.com/rugk/offline-qr-code/issues/157
