### ISSUE TITLE
Saving and copying of results.

### ISSUE THREAD

**Issue by jtagcat** [rugk/offline-qr-code#267]
#40 changes don't exist anymore. There has been not tip for saving QR codes.

Right now, when attempting to right-click a generated QR code, I can't copy the image nor save it.

And-or allow right-clicking on the image; add buttons to copy/save svg, png or webm (convert to rasterized, many places can't do svg).

**Comment by rugk** [comment]
Hi and thanks for the report,
> Right now, when attempting to right-click a generated QR code, I can't copy the image nor save it.

Actually the feature is still there. See the FAQ, it's just a submenu: https://github.com/rugk/offline-qr-code/wiki/FAQ#how-to-save-the-qr-code-on-disk

> There has been not tip for saving QR codes.

Hmm, if you have used the add-on for some time, it will of course not be shown again and again. 
Code-wise, I just checked, and [it's still defined in here](https://github.com/rugk/offline-qr-code/blob/8b1ce7162ab3e021ef747cab4f19bc6c65370633/src/common/modules/data/Tips.js#L106-L121), so unless there is a bug, it should be shown – randomly.

> convert to rasterized, many places can't do svg

With the new versions, you do have the option to save both versions.

> add buttons to copy/save svg

That is a neat idea we also already had, but it's still in early stages. It's tracked in https://github.com/rugk/offline-qr-code/issues/225 if you want to follow.

----

Also, please mind to fill out the issue template you choose, when you open an issue the next time. This makes it easier to troubleshoot issues or understand feature requests etc.
So I'd suggest you to recheck the issues. If anyone is still happening, please report a new issue with all details.
