### ISSUE TITLE
Recreate screenhots and screencasts in new Firefox design

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#268]
The screenshots still follow the old Photon (tab) design, which of course does not

The new design [with floating tabs](https://medium.com/firefox-ux/content-design-considerations-for-the-new-firefox-44116a6ac99b) looks very much different. So all images and screencasts need to be re-made.

If anyone wants to contribute, this is a very easy task! You see all files in the [`assets/screencasts`](https://github.com/rugk/offline-qr-code/tree/master/assets/screencasts) and [`assets/screenshots`](https://github.com/rugk/offline-qr-code/tree/master/assets/screenshots)  directories. You just need to look at them and do/screenshot (exactly) the same in a new modern Firefox (stable or even Firefox Developer Edition is enough), replace all files and create and submit a Pull Request.

Also mind to keep the pixel sizes (width/height) of the GIFs/images approximately the same, as they were optimized for the display on addons.mozilla.org (AMO) etc.

**Comment by rugk** [comment]
It does not have to be exactly the same (pixel size), but the same general theme e.g. would be quite nice.
The OS does not matter.

**Comment by dialectrical** [comment]
A little busier IRL than I thought I'd be, sorry!

The English screenshots are done, just need to do the screencasts and screenshot the German settings.

**Comment by rugk** [comment]
Oh sure, thanks a lot! Did not even remember I screenshott'ed the German settings separately, that is nice.

**Comment by dialectrical** [comment]
Alright, sorry for the delay!

Pull request #271 has the new screenshots and screencaps.

**Comment by rugk** [comment]
Thanks a lot, no problem. Take the time you need. :slightly_smiling_face:

**Comment by Tch4lla** [comment]
Hi there. Is this task still available? I would like to offer my assistance if possible

**Comment by rugk** [comment]
Sure it is, so I assign it to you @Tch4lla then. :slightly_smiling_face: 

Thanks for your work already. :slightly_smiling_face:

**Comment by RohitRajvaidya5** [comment]
Is this issue resolved? I want to contribute in it.

**Comment by Tch4lla** [comment]
I have already submitted my pull request for this issue, and am currently waiting on confirmation if there are any changes or tweaks that need to be made.

**Comment by rugk** [comment]
Indeed, https://github.com/rugk/offline-qr-code/pull/284 is the PR to fix these, Sorry for the delay, I was busy and missed the notifications.

I assume, if help is needed, @RohitRajvaidya5  you can jump in and help here. Feel free to test or review the existing PR, BTW.

**Comment by Tch4lla** [comment]
I have made those adjustments and have submitted and updated pull request. I hope that it is not too much work to merge

**Comment by rugk** [comment]
Fixed by https://github.com/rugk/offline-qr-code/pull/291

(Missed linking that issue, sorry.)

@Tch4lla Next time, you can (automatically) [let issues close](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) when a PR is merged by adding some "magic" text to your PR _body_.
