### ISSUE TITLE
Spanish translation contribution

### ISSUE THREAD

**Issue by NeryGaldamez** [rugk/offline-qr-code#316]
## Spanish translation
Hi!, my name is Nery Galdámez I'm a Science and Systems Engineering student, I would like to contribute by translating to spanish any docuementation o code that is necessary, in this way we could make this proyect come to a lot more of people. If you are interest in, I will we so happy and thankfully for helping.

Spanish:
Hola! Mi nombre es Nery Galdámez, soy un estudiante de la carrera de ingeniería en Ciencias y Sistemas y me gustaría contribuir en la traducción a español de cualquier documentación o código en donde sea necesario, de esta forma podríamos hacer que este proyecto llegue a mucha más gente. Si están interesados, yo estaría muy feliz y agradecido de ayudar.

**Comment by rugk** [comment]
Thanks a lot and this is greatly appreciated!

Please refer to https://github.com/rugk/offline-qr-code/blob/master/CONTRIBUTING.md#translations for a guide on how to get started.

More general translation help is documented here: https://github.com/TinyWebEx/common/blob/master/CONTRIBUTING.md#translations

If you have any questions, feel free to ask.

**Comment by NeryGaldamez** [comment]
Hi!, sure, I will be taking a look for the information you sent. 
Just to make sure, I can modify existent translations for spanish or make my own if it´s the case. I upload my files with a pull request and you will check it, right?
Also want to say thanks for the opportunity, I will be happy to be usefull an contribute for this project.

**Comment by NeryGaldamez** [comment]
Hi!, sure, I will be taking a look for the information you sent. 
Just to make sure, I can modify existent translations for spanish or make my own if it´s the case. I upload my files with a pull request and you will check it, right?
Also want to say thanks for the opportunity, I will be happy to be usefull an contribute for this project.

**Comment by rugk** [comment]
> Just to make sure, I can modify existent translations for spanish or make my own if it´s the case. I upload my files with a pull request and you will check it, right?

Yes, exactly. If a PR is too much work for it the translation tool also has a button that creates an issue instead. a PR, however, is of course the best way to directly contribute.

**Comment by rugk** [comment]
Sure, and thanks a lot again! So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again (i.e. you can still comment).

**Comment by NeryGaldamez** [comment]
Hi! I'm repporting, I saw that some things are already translated to spanish, but I made a pull request with a minimum change y the json. Algo, I added to the Wiki an space for Spanish, because it didn´t exist before. I hope you will check it and tell if it´s good.

**Comment by rugk** [comment]
Found no PR at https://github.com/rugk/offline-qr-code/pulls?q=is%3Aopen+is%3Apr, so if you have a link that would be good.

**Comment by rugk** [comment]
Ah maybe you mean https://github.com/rugk/offline-qr-code/issues/317, but you seem to have forgotten to actually paste the translation there.

Otherwise, for information on how to propose PRs, see https://help.github.com/articles/proposing-changes-to-your-work-with-pull-requests/.
