### ISSUE TITLE
Improve Contribution documentation

### ISSUE THREAD

**Issue by elizalflores** [rugk/offline-qr-code#319]
I believe the project `README.md` and `CONTRIBUTING.md`  should include more clarifying information and directions for developers on how to contribute.

Currently there is further, nested documentation on how to contribute to the project located in the TinyWebEx project.

I plan to modify the `README.md` and `CONTRIBUTING.md` to help give more information about these additional guidelines.

**Comment by rugk** [comment]
Sure do a PR; but from your description it is not really clear what you want to modify.

Note the big parts should be into the "nested" TinyWebEx contrib doc, as this applies to all extensions and I don't want to maintain that change in each extension.
