### ISSUE TITLE
Spanish AMO summary translation is too long

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#330]
The AMO summary texts are limited to 250 characters. The Spanish translation is currently too long.

I shortened it now to:
> Esta extensión te permite generar rápidamente códigos QR offline de una URL abierta en tus pestañas o cualquier texto (seleccionado)! 👍
>
>Funciona completamente offline protegiendo así tu privacidad!

See https://github.com/rugk/offline-qr-code/commit/549ab3316a2ab037e5507ca62e01d03570155055 for more information.

But @Fanksies / @bryancalisto / dverbru FYI if you wanna correct it or provide a better short translation, feel free to create a PR.

**Comment by bryancalisto** [comment]
Hey rugk, I didn't saw this earlier. I just set this [PR](https://github.com/rugk/offline-qr-code/pull/333)  up for this
