### ISSUE TITLE
Adjust and group options style with headers like Firefox

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#43]
Using `about:preferences` as a template, the aim should be to have something simlar from a grouping perspective.

This also means to drop `fieldset`s (the border around the radio options as a "radio group").

See https://design.firefox.com/photon/visuals/grid.html

**Comment by ongspxm** [comment]
hmm... any work to be done on this? what do u mean grouping perspective?

**Comment by rugk** [comment]
No, this is still to be solved…

What I mean is best explained on https://design.firefox.com/photon/visuals/grid.html#spacing. I just want to group the options into some useful categories…
When you want to take this on, just make sure you follow the above linked Firefox Photon style exactly. :smile: 

As said `about:preferences` can be used as a visual template, i.e. it should look similar to there.
