### ISSUE TITLE
Support special links (tel: / mailto:)

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#62]
Currently only "standard" HTML&/website links are supported.

It would be good if we could support other link types, too.

```
<a href="mailto:nowhere@mozilla.org?cc=name2@rapidtables.com&bcc=name3@rapidtables.com&subject=The%20subject%20of%20the%20email&body=The%20body%20of%20the%20email">
  Send mail with cc, bcc, subject and body
</a>
```

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#E-mail_links

[mail link](mailto:nowhere@mozilla.org)

```
<a href="tel:18475555555">Click Here To Call Support 1-847-555-5555</a> 
```

http://allwebco-templates.com/support/S_smartphone-link.htm

Depends on https://github.com/rugk/offline-qr-code/issues/61.

**Comment by ENT8R** [comment]
At least ZXing parses it automatically. You can try it also here: https://zxing.org/w/decode.jspx with the following screenshots:
<img src="https://user-images.githubusercontent.com/25306497/40270665-9a3499d4-5b91-11e8-8968-60c19b819da2.png" width="250px"> <img src="https://user-images.githubusercontent.com/25306497/40270664-9a0db7ce-5b91-11e8-8dcf-cece93c63b27.png" width="250px">

I also have a question regarding your first example with the `mailto `link: should then the leading `mailto:` **and** the trailing additional information like subject and so on be removed? Or should the URL parameters stay where they are?

**Comment by rugk** [comment]
> At least ZXing parses it automatically.

Oh, wait, yeah… that could be right. I forgot, indeed. Is that the correct format for QR codes like that?

In this case, this issue might just be obsolete.

We could do the reverse, i.e. detect whether a text is a e-mail address or a phone number and ad the appropriate prefix, but this is very fragile (creepy regex expressions would need to be used, and localized) and not really possible in a sane way.

So unless anyone has any other suggestions, I'll close this issue.
