### ISSUE TITLE
Customizable hot key

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#67]
Depends on https://github.com/rugk/offline-qr-code/issues/54

Task: Make hotkey actually customizable…

This requires a decent UI/input method. The simplest thing would be text input, but that is rather odd from a users'/usability perspective. Catching all keys the user presses as an input method may be the thing we want (i.e. user clicks on button -> box "Press the key you want to assign." -> User presses some hot key combination.).

Actually changing the hot key is possible with https://developer.mozilla.org/de/Add-ons/WebExtensions/API/commands/update.

**Comment by h-h-h-h** [comment]
I would like to be able to disable the hotkey to reduce possible conflicts.

**Comment by h-h-h-h** [comment]
> I e.g. don't know how Firefox handles it if there is a conflict. Maybe my add-on does not even get the hotkey...

You could easily test that by temporarily assigning a simple already existing hotkey to your add-on.

> What does it actually conflict with?

There is none I know of. But in an ecosystem, where different parts aren't governed by a single group or person, I think, shortcuts should be opt-in, or at least opt-out. All those cryptic shortcut definitions by various authors that -- naturally -- don't communicate with each other, can be likened to context menu clutter, in my opinion.

**Comment by rugk** [comment]
> can be likened to context menu clutter, in my opinion.

Except that you have no "clutter" here, but rather having one hotkey that likely takes precedence… 

> You could easily test that by temporarily assigning a simple already existing hotkey to your add-on.

Yeah, good idea, I may try. Or do you want?

**Comment by h-h-h-h** [comment]
> Or do you want?

I can't do it currently.

**Comment by rugk** [comment]
Changing it to `Ctrl+V` on Windows, it only works on `about:debugging`, nowhere else.

[The doc](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Key_combinations) also says:
> If a key combination is already used by the browser (for example, "Ctrl+P"), or by an existing add-on, then you can't override it. You will be allowed to define it, but your event handler will not be called when the user enters it.

Thus, it really seems to depend on the order the add-ons are loaded, or - in case of any system hotkeys - they always come first.

**Comment by rugk** [comment]
Great news!
I just heart this issue will be obsolete in Firefox 66!

DE: https://www.soeren-hentzschel.at/firefox/tastatur-kommandos-von-erweiterungen-koennen-ab-firefox-66-geaendert-werden/
 https://bugzilla.mozilla.org/show_bug.cgi?id=1303384

**Comment by rugk** [comment]
FYI this is how it looks now:
![image](https://user-images.githubusercontent.com/11966684/51429733-d2502400-1c11-11e9-91ad-251744e83287.png)
