### ISSUE TITLE
Use CSS variables

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#68]
We do have really too many hardcoded CSS values… (especially colors and stuff, which has assigned names in the Photon design guide)

So this needs to be changed.

See:
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables

IMHO all variables can be created in the `common.css` to have them in one place even if we might not use them in all cases.

**Comment by anirudh-modi** [comment]
Hey @rugk ,

I am looking for my first open source contribution, I would like to complete this task. 
Below is the list of css variable names which is assigned in Photon design guides.

https://firefoxux.github.io/design-tokens/photon-colors/photon-colors.css

Kindly let me know if these are the variables naming conventions which needs to be followed? 

And should I make the desired changes in `common.css` for declaration of variables and then go on to change color in files mentioned below :
* `common.css`
* `options.css`
*  `qrcode.css`

Thanks!
Anirudh

**Comment by anirudh-modi** [comment]
Shall there be css variable for font size also??

https://design.firefox.com/photon/visuals/typography.html

There some of the naming defined here in the link above, however it seems as the styling depends on the os environment.

**Comment by anirudh-modi** [comment]
Also looks like we need to create a copy of Mozilla Public License, v. 2.0. Correct me if I am wrong about it.

**Comment by rugk** [comment]
Hi @anirudh-modi,
thanks for your interest in contributing to this project! :tada: :+1: 
I hope you'll like this project and can enjoy hacking on it… :smiley:

> Kindly let me know if these are the variables naming conventions which needs to be followed?

Just use the style, the Firefox photon guide uses. So we don't need any conversion of the variable names here, that makes copy and past easier. :wink: 

> And should I make the desired changes in common.css for declaration of variables and then go on to change color in files mentioned below

Indeed, that's what I imagine. :+1: 

> Shall there be css variable for font size also??

Good question, but I don't think so. Firstly currently I use some custom sizes, which just match the text size the Firefox add-on settings page uses, so it may not actually be covered in that guide.
Secondly, the Photon guide says it is different from OS and then you have all these variants (weight and stuff…), so i think it is not worth it currently.

**Comment by anirudh-modi** [comment]
Hi @rugk,

Thanks alot for the information, I shall assign this task to myself and do the needful.

**Comment by rugk** [comment]
FYI you can link to lines on GitHub, but I guess you copied them from a text editor, so…

> ` background-color: #d70022ee;`

Yes, that last part is just an added transparency. Apart from that it is the error color, which is defined and known in Photon. Maybe you'll find a way to combine the vars? So that the transparent color can just reference the "base color", but add transparency? (If not, they yeah… maybe you have to create a new var then – just keep the name similar to the "base" one, then.)

> `color: #333;`

Yeah, that's just the color extracted from the add-on settings pane (as indicated by the comment aboe :wink:). It's funny that Firefox does not always adhere to their own guide, too.
But IMHO you don't need a var for that. It should only be used in this one place, anyway, so you can keep it hard-coded.

> should I go ahead put all the colors, for future usage?

I have no strong option on this, especially as the style sheet is small, but actually I'd rather tend to pick out the colors we use. We only use 4 or 5, so including the whole style sheet may not be necessary.

**Comment by anirudh-modi** [comment]
Since the base color was defined in hex I could not use rgba to generate the error background witha transparency, and since in the Photon guide they didnt declared the base color in rgb format, to maintain consistency I have declared a new var named `--red-60-93` following the convention used in  photon. Hope that is ok.

**Comment by rugk** [comment]
I'll continue the discussion in the PR…

**Comment by anirudh-modi** [comment]
Ok.

**Comment by rugk** [comment]
Fixed by https://github.com/rugk/offline-qr-code/pull/80

BTW next time you can (automatically) [let issues close](https://help.github.com/articles/closing-issues-via-commit-messages/) when a PR is merged.
