### ISSUE TITLE
Display error/warning for too large input

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#72]
I think the size can be hardcoded… (in a const of course)

https://en.wikipedia.org/wiki/QR_code#Storage

Currently it will just show an empty area…

**Comment by ongspxm** [comment]
Im interested in working on this issue, is this still required?

**Comment by rugk** [comment]
Yes, sure, feel free to take it on.

Some steps/requirements:
* We need to find out, how many characters can fit into a QR code? I mean, I already linked Wikipedia, but possibly there are still other issues, e.g. the used QR code generation libs may have their own limits.
   This just needs some testing.
* (Obviously) it should always allow the maximum number of characters, so users can use it up to the limit.
* Show an appropriate error & the usual QR placeholder image (likely done automatically) if this happens-
* _Possibly_ offer a useful "solution"/"mitigation" for the user as an "action button": E.g. crop the text?
   Think of the use cases that might result in that error. Maybe you can come up with another clever idea.
* Hide error again if length is okay again.
* **If needed**, we maybe need a FAQ, but this depends on what limits there actually are and whether we need to explain something/there is any value in explaining it to the user.

Or solve it differently: Instead of hardcoding limits, use some try/catch(-like) thing to try the QR code generation and only detect an error, so you just can prevent the "broken empty image". If that is possible :thinking:… Your implementation, your choice…

In the PR, just explain what you did/tried or so.

**Comment by ongspxm** [comment]
I am on master branch, i ran the make.sh, and got a .xdi file. But when i tried to put that into firefox, it tells me its corrupted, i assume there is a separate step to install it locally?

**Comment by rugk** [comment]
Sorry got the late reply, seems to have missed the comment.

So important: You _do not_ need to run the make script. That is only used for releases.

Just follow the "getting started" section of the contributing guide instead. With it, you need nothing more than Firefox to develop. ☺

(Seems I should really put that note into the contributing guide. This misunderstanding came up before.)

**Comment by ongspxm** [comment]
oh nice, i placed the manifest file in, and it seems to load. i am loading master version of the code, it should work in firefox version 65 without having to do anything right? am i missing some step, i followed all of the steps

![test](https://user-images.githubusercontent.com/1430854/53960453-55c1c800-4121-11e9-9113-3abfcfde75e9.gif)
![test](https://user-images.githubusercontent.com/1430854/53960454-55c1c800-4121-11e9-89bc-505977667dd1.jpg)

**Comment by ongspxm** [comment]
pr opened, ready for review
