### ISSUE TITLE
Quiet zone setting

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#77]
## Background

Currently the ["quiet zone"](https://qrworld.wordpress.com/2011/08/09/the-quiet-zone/) ([Wikipedia](https://en.wikipedia.org/wiki/QR_code#Standards)) is "managed" by CSS as a padding with `20px`. This is fixed, and does not change with the size. (kjua may add some more due to "crisp" setting, but that does not matter)

## Use case

Practically I had no problems with that approach in my tests, but there is one use case, where it looks ugly: When you save the QR code image.

Of course, it is easy to add a "padding" (aka "empty area") in whatever program you later use the QR code, but it is at least strange to get the QR code in such a way and maybe users may forget it when printing it later or whatever…

## ToDo

So, IMHO, we need a new setting for the quiet zone:
* as for the design it can be a slider as shown on https://larsjung.de/kjua/latest/demo/
* default: 0, up to 10 or so as in kjua demo linked above
* if enabled, it _may_ disable the padding of CSS; as this is quite redundant then (but maybe it does not look so bad either?)
* the setting should have a helper text linking to a useful resource (Wikipedia might be a bit few, the blog I linked too much – maybe requires https://github.com/rugk/offline-qr-code/issues/65)

**Comment by xlomonosvx** [comment]
im gonna work on it

**Comment by rugk** [comment]
Okay, great, feel free to ask if you have any questions. :smiley:

**Comment by xlomonosvx** [comment]
done

**Comment by rugk** [comment]
Fixed with https://github.com/rugk/offline-qr-code/pull/129
