### ISSUE TITLE
Refactor RandomTips to only load options when tip is going to be shown

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#84]
Currently the options of `RandomTips` are loaded at startup directly in the `init` functions and only after this is done the tip may be shown – or not (randomly)…

This is of course a bit wasting resources* to request the options if they are not actually needed.

So if one wants you may refactor it, you can do so. It's not a big thing, as it works currently, but certainly a little nice improvement.
This may require some basic knowledge of promises.

Requirements:
* of course, do not re-load the options, if they have been loaded already
* load when a tip is to be shown (i.e. after random selection, or when `showRandomTip` is called directly)

\* practially all options are fetched anyway, but well… it still makes no sense.

**Comment by c3ho** [comment]
Hi, is it possible to work on this issue?

**Comment by rugk** [comment]
No sorry, because @daaAd1 already solved it/is solving it in https://github.com/rugk/offline-qr-code/pull/221. Please do have a look at the links provided in the issue. (the PR was linked above your comment)

You may have a look at [all issues tagged with "hacktoberfest" in this repo](../issues/labels/hacktoberfest) or [somewhere else](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Arugk+user%3ATinyWebEx+label%3A%22hacktoberfest%22+).

**Comment by c3ho** [comment]
Totally, missed that. Thank you for the quick reply!
