### ISSUE TITLE
Should show error if tabs cannot be retrieved

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#89]
This e.g. happens like this (STR):
1. Open a new tab and load some website.
2. While it loads quickly open/click on the QR code popup.

What happens:
It seems it cannot get the tabs and just shows a loading message.

What should happen:
It should show an error instead.

I guess the fix should be quite easy, but involves some stuff with Promises, so you need knowledge in that. Reproducing may be the hardest of this issue, as it requires some good timing… :wink: 

(also only reproduced with an old version; some stuff has changed since that, maybe it is actually already fixed; in this case, it just requires a conformation that this is fixed.)

**Comment by krishnan2098** [comment]
I would love to help but i dont know how to start because i am a newbie

**Comment by rugk** [comment]
Well… first of all you need to reproduce the issue. Can you do so with the current version?

If so follow [this guide](https://github.com/rugk/offline-qr-code/blob/master/CONTRIBUTING.md#getting-started) to test it with the latest version. Still reproducible? Then you can try to find the root cause. Cannot reproduce? Then it has been fixed in the mean time and you can jsut comment here and say it seems it has been fixed and this can be closed.

If you need to debug it, look somewhere around here:
https://github.com/rugk/offline-qr-code/blob/master/src/popup/qrcode.js#L1092

This is the line that should actually display the error. Maybe the code does not reach that part? Best thing would be to try using [the debugger](https://mozilladevelopers.github.io/playground/debugger/) to find out what happens in this case and why it does not show this error.

**Comment by krishnan2098** [comment]
It seems it has been fixed as I have cloned the latest version in my local machine and tested it a few times and the wasn't any error, is there anything else where I can help you?

**Comment by rugk** [comment]
> and the wasn't any error,

Ehm… well, this issue would be fixed if _there is_ an error. Maybe read the STR again (https://github.com/rugk/offline-qr-code/issues/89#issue-324654755), this issue here is about showing an error, when it

**Comment by krishnan2098** [comment]
### This is what it shows. There isn't any error message or warning about it.

![screenshot from 2018-05-26 18-55-43](https://user-images.githubusercontent.com/26490172/40576586-9b51ac78-6116-11e8-812d-7a899cb64139.png)

**Comment by rugk** [comment]
And the QR code reads `undefined`. Yes, that is definitely a bug… it should show an error.

However, how did you trigger it? You do not seem to have opened it while the Google search page was shown.

**Comment by krishnan2098** [comment]
I clicked the extension button when the Google search page was not completely loaded. That's how this bug has occurred.
