### ISSUE TITLE
Check contrast while picking the color

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#95]
I already implemented it, this is just for documentation/to show this change in the live version:

![contrastlivecheck](https://user-images.githubusercontent.com/11966684/40878448-b55d4bec-6691-11e8-8efe-e264ed4fddf9.gif)

I think it actually makes the whole self-check more useful, as users can then manually evaluate what contrast they want/manually select the contrast they need. 

Actually I noticed you can even **click the action button** (to calculate the contrast value) in the background when the "Select color" picker dialog is still open. That is funny, but actually useful. I had to adjust the JS a bit to take this into account, but now it works.
The crazies thing in my tests is: Yes, you can open **both** color pickers and manually change/compare the colors. It works! :laughing: 

Generally the color picker depends on the OS in Firefox, so it would be great to get some tests on other OSes from some people. Does the thing work in general as you can see it in my GIF? And does the thing I described above work – clicking on the button in the background while changing the color?

/cc @ENT8R, BTW :smile: 

(follow-up of https://github.com/rugk/offline-qr-code/issues/19)

**Comment by rugk** [comment]
As explained above, it would be great to get some feedback on how this works on different OSes, thus I reopen this issue.

**Comment by ENT8R** [comment]
I can test it on my Windows machine as soon as possible (Don't know if I can do that today but tomorrow should be no problem)

**Comment by ENT8R** [comment]
> Does the thing work in general as you can see it in my GIF?

Yes, also on Windows the message gets automatically updated if you select another color

> And does the thing I described above work – clicking on the button in the background while changing the color?

No, this does not work at all. If I click anywhere else than inside of the color picker I can only hear a [windows error sound](https://www.youtube.com/watch?v=lNwnftRb9v0)

> Yes, you can open both color pickers

This does not work too...

**Comment by rugk** [comment]
Well… okay…yeah. At least the main feature works, that's enough. :smile:

**Comment by rugk** [comment]
Well… okay…yeah. At least the main feature works, that's enough. :smile:

**Comment by rugk** [comment]
@Wikinaut maybe wanna test on MacOS?
