### ISSUE TITLE
Show contrast error message next to actual color settings

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#96]
Follow-up of https://github.com/rugk/offline-qr-code/issues/95 and https://github.com/rugk/offline-qr-code/issues/19

Currently the error is just shown at the top. However, it would of course be more useful to actually show it next to the actual settings you modify somehow.
Often the error message may even not be visible, because the user scrolled down too much.

**Comment by rugk** [comment]
With the _MessageHandler_ module and especially the [custom messages](https://github.com/TinyWebEx/MessageHandler#custom-messages) this should now be actually very straightforward to implement.

As such, I'll mark it as a good first issue. :smiley:

**Comment by daaAd1** [comment]
Hi, can i work on this?

**Comment by rugk** [comment]
Of course, feel free to take this one. 😃

**Comment by rugk** [comment]
Fixed by https://github.com/rugk/offline-qr-code/pull/219
