### ISSUE TITLE
Recover from still loading tab

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#98]
After the fix of https://github.com/rugk/offline-qr-code/issues/89 it now just shows an error if the tab could not be got.

It would be better though, if it could at least retry (with a timeout!) getting the tab URL when the tab is still loading. This is likely nicer than just showing an error, just because of some internal errors…

How-to: https://github.com/mdn/webextensions-examples/blob/8694314d5a328616f028bb71e4d6bbd352375440/session-state/background.js#L37-L51

**Comment by OogieBoogieInJSON** [comment]
I'll pick this up.

**Comment by rugk** [comment]
Great! If you have any questions, feel free to ask. :smiley:

**Comment by rugk** [comment]
Should theoretically fixed by https://github.com/rugk/offline-qr-code/pull/115, but that does not work and is currently blocked by a Firefox bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1479903).

**Comment by rugk** [comment]
Okay, what we are trying to accomplish seems to be not possible withe the `activeTab`permission. See [the reply in the bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1479903#c5). As such, I think I'd have to revert the added behaviour as it won't work anyway. 😐
